export interface GameConfig {
  height: number;
  width: number;
  backgroundColor: string;
}

export type UI_CONFIG_BLANK_TYPE = '';
export type UI_CONFIG_TITLE_TYPE = 'UI_CONFIG_TITLE';
export type UI_CONFIG_REVEALED_PATTERN_TYPE = 'UI_CONFIG_REVEALED_PATTERN';
export type UI_CONFIG_PATH_ANSWER_TYPE = 'UI_CONFIG_PATH_ANSWER';
export type UI_CONFIG_PATH_GUESS_LABEL_TYPE = 'UI_CONFIG_PATH_GUESS_LABEL';
export type UI_CONFIG_GAME_BOARD_TYPE = 'UI_CONFIG_GAME_BOARD';
export type UI_CONFIG_GAME_DESCRIPTION_TYPE = 'UI_CONFIG_GAME_DESCRIPTION';
export type UI_CONFIG_NEW_GAME_BUTTON_TYPE = 'UI_CONFIG_NEW_GAME_BUTTON';
export type UI_CONFIG_GAME_UI_BUTTON_GROUP_TYPE = 'UI_CONFIG_GAME_UI_BUTTON_GROUP';
export type UI_CONFIG_TRIES_COLLECTION_TYPE = 'UI_CONFIG_TRIES_COLLECTION';
export type UI_CONFIG_TRIES_LEFT_LABEL_TYPE = 'UI_CONFIG_TRIES_LEFT_LABEL';
export type UI_CONFIG_SHOW_SOLUTION_BUTTON_TYPE = 'UI_CONFIG_SHOW_SOLUTION_BUTTON';

export const UI_CONFIG_BLANK: UI_CONFIG_BLANK_TYPE = '';
export const UI_CONFIG_TITLE: UI_CONFIG_TITLE_TYPE = 'UI_CONFIG_TITLE';
export const UI_CONFIG_REVEALED_PATTERN: UI_CONFIG_REVEALED_PATTERN_TYPE = 'UI_CONFIG_REVEALED_PATTERN';
export const UI_CONFIG_PATH_ANSWER: UI_CONFIG_PATH_ANSWER_TYPE = 'UI_CONFIG_PATH_ANSWER';
export const UI_CONFIG_PATH_GUESS_LABEL: UI_CONFIG_PATH_GUESS_LABEL_TYPE = 'UI_CONFIG_PATH_GUESS_LABEL';
export const UI_CONFIG_GAME_BOARD: UI_CONFIG_GAME_BOARD_TYPE = 'UI_CONFIG_GAME_BOARD';
export const UI_CONFIG_GAME_DESCRIPTION: UI_CONFIG_GAME_DESCRIPTION_TYPE = 'UI_CONFIG_GAME_DESCRIPTION';
export const UI_CONFIG_NEW_GAME_BUTTON: UI_CONFIG_NEW_GAME_BUTTON_TYPE = 'UI_CONFIG_NEW_GAME_BUTTON';
export const UI_CONFIG_GAME_UI_BUTTON_GROUP: UI_CONFIG_GAME_UI_BUTTON_GROUP_TYPE = 'UI_CONFIG_GAME_UI_BUTTON_GROUP';
export const UI_CONFIG_TRIES_COLLECTION: UI_CONFIG_TRIES_COLLECTION_TYPE = 'UI_CONFIG_TRIES_COLLECTION';
export const UI_CONFIG_TRIES_LEFT_LABEL: UI_CONFIG_TRIES_LEFT_LABEL_TYPE = 'UI_CONFIG_TRIES_LEFT_LABEL';
export const UI_CONFIG_SHOW_SOLUTION_BUTTON: UI_CONFIG_SHOW_SOLUTION_BUTTON_TYPE = 'UI_CONFIG_SHOW_SOLUTION_BUTTON';

export type UI_CONFIG_KEY = UI_CONFIG_TITLE_TYPE
  | UI_CONFIG_REVEALED_PATTERN_TYPE
  | UI_CONFIG_PATH_ANSWER_TYPE
  | UI_CONFIG_PATH_GUESS_LABEL_TYPE
  | UI_CONFIG_GAME_BOARD_TYPE
  | UI_CONFIG_GAME_DESCRIPTION_TYPE
  | UI_CONFIG_NEW_GAME_BUTTON_TYPE
  | UI_CONFIG_GAME_UI_BUTTON_GROUP_TYPE
  | UI_CONFIG_TRIES_COLLECTION_TYPE
  | UI_CONFIG_TRIES_LEFT_LABEL_TYPE
  | UI_CONFIG_SHOW_SOLUTION_BUTTON_TYPE
  | UI_CONFIG_BLANK_TYPE;

export type UI_CONFIG_TYPE = {
  key: UI_CONFIG_KEY;
  x: number;
  y: number;
};

export const UI_CONFIG: UI_CONFIG_TYPE[] = [
  {
    key: UI_CONFIG_TITLE,
    x: 360,
    y: 100
  },
  {
    key: UI_CONFIG_REVEALED_PATTERN,
    x: 360,
    y: 300
  },
  {
    key: UI_CONFIG_PATH_ANSWER,
    x: 32,
    y: 117
  },
  {
    key: UI_CONFIG_GAME_BOARD,
    x: 132,
    y: 725
  },
  {
    key: UI_CONFIG_GAME_DESCRIPTION,
    x: 16,
    y: 100
  },
  {
    key: UI_CONFIG_NEW_GAME_BUTTON,
    x: 180,
    y: 80
  },
  {
    key: UI_CONFIG_SHOW_SOLUTION_BUTTON,
    x: 180,
    y: 200
  },
  {
    key: UI_CONFIG_TRIES_COLLECTION,
    x: 380,
    y: 40
  },
  {
    key: UI_CONFIG_TRIES_LEFT_LABEL,
    x: 16,
    y: 50
  },
  {
    key: UI_CONFIG_PATH_GUESS_LABEL,
    x: 44,
    y: 550
  },
]